// Code generated by protoc-gen-go. DO NOT EDIT.
// source: poll-summary.proto

package voting

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PollOptionSummary struct {
	Option               *Option  `protobuf:"bytes,1,opt,name=Option,proto3" json:"Option,omitempty"`
	VoteCounts           int32    `protobuf:"varint,2,opt,name=VoteCounts,proto3" json:"VoteCounts,omitempty"`
	Ratio                float32  `protobuf:"fixed32,3,opt,name=Ratio,proto3" json:"Ratio,omitempty"`
	Rank                 int32    `protobuf:"varint,4,opt,name=Rank,proto3" json:"Rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollOptionSummary) Reset()         { *m = PollOptionSummary{} }
func (m *PollOptionSummary) String() string { return proto.CompactTextString(m) }
func (*PollOptionSummary) ProtoMessage()    {}
func (*PollOptionSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce39fd6f55b4c338, []int{0}
}

func (m *PollOptionSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollOptionSummary.Unmarshal(m, b)
}
func (m *PollOptionSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollOptionSummary.Marshal(b, m, deterministic)
}
func (m *PollOptionSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollOptionSummary.Merge(m, src)
}
func (m *PollOptionSummary) XXX_Size() int {
	return xxx_messageInfo_PollOptionSummary.Size(m)
}
func (m *PollOptionSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PollOptionSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PollOptionSummary proto.InternalMessageInfo

func (m *PollOptionSummary) GetOption() *Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *PollOptionSummary) GetVoteCounts() int32 {
	if m != nil {
		return m.VoteCounts
	}
	return 0
}

func (m *PollOptionSummary) GetRatio() float32 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

func (m *PollOptionSummary) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type PollSummary struct {
	Poll                 *Poll                `protobuf:"bytes,1,opt,name=Poll,proto3" json:"Poll,omitempty"`
	TotalVotes           int32                `protobuf:"varint,2,opt,name=TotalVotes,proto3" json:"TotalVotes,omitempty"`
	Options              []*PollOptionSummary `protobuf:"bytes,3,rep,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PollSummary) Reset()         { *m = PollSummary{} }
func (m *PollSummary) String() string { return proto.CompactTextString(m) }
func (*PollSummary) ProtoMessage()    {}
func (*PollSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce39fd6f55b4c338, []int{1}
}

func (m *PollSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollSummary.Unmarshal(m, b)
}
func (m *PollSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollSummary.Marshal(b, m, deterministic)
}
func (m *PollSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollSummary.Merge(m, src)
}
func (m *PollSummary) XXX_Size() int {
	return xxx_messageInfo_PollSummary.Size(m)
}
func (m *PollSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PollSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PollSummary proto.InternalMessageInfo

func (m *PollSummary) GetPoll() *Poll {
	if m != nil {
		return m.Poll
	}
	return nil
}

func (m *PollSummary) GetTotalVotes() int32 {
	if m != nil {
		return m.TotalVotes
	}
	return 0
}

func (m *PollSummary) GetOptions() []*PollOptionSummary {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetPollSummaryResponse struct {
	Error                bool         `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Value                *PollSummary `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPollSummaryResponse) Reset()         { *m = GetPollSummaryResponse{} }
func (m *GetPollSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*GetPollSummaryResponse) ProtoMessage()    {}
func (*GetPollSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce39fd6f55b4c338, []int{2}
}

func (m *GetPollSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPollSummaryResponse.Unmarshal(m, b)
}
func (m *GetPollSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPollSummaryResponse.Marshal(b, m, deterministic)
}
func (m *GetPollSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPollSummaryResponse.Merge(m, src)
}
func (m *GetPollSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_GetPollSummaryResponse.Size(m)
}
func (m *GetPollSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPollSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPollSummaryResponse proto.InternalMessageInfo

func (m *GetPollSummaryResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *GetPollSummaryResponse) GetValue() *PollSummary {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*PollOptionSummary)(nil), "voting.summary.PollOptionSummary")
	proto.RegisterType((*PollSummary)(nil), "voting.summary.PollSummary")
	proto.RegisterType((*GetPollSummaryResponse)(nil), "voting.summary.GetPollSummaryResponse")
}

func init() { proto.RegisterFile("poll-summary.proto", fileDescriptor_ce39fd6f55b4c338) }

var fileDescriptor_ce39fd6f55b4c338 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0xbe, 0xfd, 0xcb, 0xe4, 0x4f, 0xa1, 0xe3, 0x0b, 0xa1, 0x82, 0xc4, 0x1e, 0x34,
	0x97, 0x06, 0x8d, 0x47, 0x6f, 0x8a, 0xf4, 0x24, 0xca, 0x56, 0x7a, 0xf0, 0xb6, 0xea, 0x22, 0xc1,
	0x4d, 0x26, 0x6c, 0xb6, 0x05, 0xbf, 0x83, 0x37, 0xbf, 0x86, 0x1f, 0x52, 0x76, 0x37, 0xd5, 0xb6,
	0x56, 0xbd, 0x65, 0x9e, 0x79, 0x66, 0x9e, 0x5f, 0x86, 0x05, 0x2c, 0x49, 0xa9, 0x51, 0x35, 0xcb,
	0x73, 0xa1, 0x5f, 0x92, 0x52, 0x93, 0x21, 0xec, 0xcd, 0xc9, 0x64, 0xc5, 0x53, 0x52, 0xab, 0x83,
	0xff, 0x39, 0x3d, 0x4a, 0x55, 0xf9, 0xee, 0xf0, 0x95, 0x41, 0xff, 0x86, 0x94, 0xba, 0x2e, 0x4d,
	0x46, 0xc5, 0xc4, 0x7b, 0x70, 0x04, 0x1d, 0x2f, 0x84, 0x2c, 0x62, 0x71, 0x90, 0xee, 0x24, 0xf5,
	0x92, 0x7a, 0xd6, 0x37, 0x79, 0x6d, 0xc2, 0x7d, 0x80, 0x29, 0x19, 0x79, 0x41, 0xb3, 0xc2, 0x54,
	0x61, 0x23, 0x62, 0x71, 0x9b, 0x2f, 0x29, 0xb8, 0x0d, 0x6d, 0x2e, 0x4c, 0x46, 0x61, 0x33, 0x62,
	0x71, 0x83, 0xfb, 0x02, 0x11, 0x5a, 0x5c, 0x14, 0xcf, 0x61, 0xcb, 0xf9, 0xdd, 0xf7, 0xf0, 0x8d,
	0x41, 0x60, 0x71, 0x16, 0x20, 0x47, 0xd0, 0xb2, 0x65, 0x8d, 0xb1, 0xb5, 0x86, 0x61, 0x5b, 0xdc,
	0x19, 0x2c, 0xc2, 0x2d, 0x19, 0xa1, 0x6c, 0xea, 0x27, 0xc2, 0x97, 0x82, 0x67, 0xf0, 0xcf, 0xc3,
	0x56, 0x61, 0x33, 0x6a, 0xc6, 0x41, 0x7a, 0x90, 0xac, 0xde, 0x25, 0xf9, 0x76, 0x05, 0xbe, 0x98,
	0x18, 0x0a, 0xd8, 0x1d, 0x4b, 0xb3, 0xc4, 0xc5, 0x65, 0x55, 0x52, 0x51, 0x49, 0xfb, 0x67, 0x97,
	0x5a, 0x93, 0x76, 0x80, 0x5d, 0xee, 0x0b, 0x3c, 0x81, 0xf6, 0x54, 0xa8, 0x99, 0x74, 0x1c, 0x41,
	0xba, 0xb7, 0x29, 0x6a, 0xb1, 0xc9, 0x3b, 0xd3, 0x77, 0x06, 0xb8, 0x24, 0x4f, 0xa4, 0x9e, 0x67,
	0x0f, 0x12, 0xaf, 0xa0, 0xb7, 0x9a, 0x8c, 0x9b, 0x6e, 0x30, 0x38, 0x5c, 0x4f, 0xf8, 0x01, 0x77,
	0x0c, 0xfd, 0x89, 0xd1, 0x52, 0xe4, 0x7f, 0x6e, 0xfc, 0x8d, 0xf9, 0x98, 0x9d, 0x77, 0xef, 0x3a,
	0xbe, 0x7f, 0xdf, 0x71, 0xef, 0xe8, 0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xad, 0x3a, 0xd0,
	0x7b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PollSummaryServiceClient is the client API for PollSummaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PollSummaryServiceClient interface {
	GetPollSummary(ctx context.Context, in *Poll, opts ...grpc.CallOption) (*GetPollSummaryResponse, error)
	StreamPollSummary(ctx context.Context, in *Poll, opts ...grpc.CallOption) (PollSummaryService_StreamPollSummaryClient, error)
}

type pollSummaryServiceClient struct {
	cc *grpc.ClientConn
}

func NewPollSummaryServiceClient(cc *grpc.ClientConn) PollSummaryServiceClient {
	return &pollSummaryServiceClient{cc}
}

func (c *pollSummaryServiceClient) GetPollSummary(ctx context.Context, in *Poll, opts ...grpc.CallOption) (*GetPollSummaryResponse, error) {
	out := new(GetPollSummaryResponse)
	err := c.cc.Invoke(ctx, "/voting.summary.PollSummaryService/GetPollSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollSummaryServiceClient) StreamPollSummary(ctx context.Context, in *Poll, opts ...grpc.CallOption) (PollSummaryService_StreamPollSummaryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PollSummaryService_serviceDesc.Streams[0], "/voting.summary.PollSummaryService/StreamPollSummary", opts...)
	if err != nil {
		return nil, err
	}
	x := &pollSummaryServiceStreamPollSummaryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PollSummaryService_StreamPollSummaryClient interface {
	Recv() (*PollSummary, error)
	grpc.ClientStream
}

type pollSummaryServiceStreamPollSummaryClient struct {
	grpc.ClientStream
}

func (x *pollSummaryServiceStreamPollSummaryClient) Recv() (*PollSummary, error) {
	m := new(PollSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PollSummaryServiceServer is the server API for PollSummaryService service.
type PollSummaryServiceServer interface {
	GetPollSummary(context.Context, *Poll) (*GetPollSummaryResponse, error)
	StreamPollSummary(*Poll, PollSummaryService_StreamPollSummaryServer) error
}

// UnimplementedPollSummaryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPollSummaryServiceServer struct {
}

func (*UnimplementedPollSummaryServiceServer) GetPollSummary(ctx context.Context, req *Poll) (*GetPollSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPollSummary not implemented")
}
func (*UnimplementedPollSummaryServiceServer) StreamPollSummary(req *Poll, srv PollSummaryService_StreamPollSummaryServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPollSummary not implemented")
}

func RegisterPollSummaryServiceServer(s *grpc.Server, srv PollSummaryServiceServer) {
	s.RegisterService(&_PollSummaryService_serviceDesc, srv)
}

func _PollSummaryService_GetPollSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Poll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollSummaryServiceServer).GetPollSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.summary.PollSummaryService/GetPollSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollSummaryServiceServer).GetPollSummary(ctx, req.(*Poll))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollSummaryService_StreamPollSummary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Poll)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PollSummaryServiceServer).StreamPollSummary(m, &pollSummaryServiceStreamPollSummaryServer{stream})
}

type PollSummaryService_StreamPollSummaryServer interface {
	Send(*PollSummary) error
	grpc.ServerStream
}

type pollSummaryServiceStreamPollSummaryServer struct {
	grpc.ServerStream
}

func (x *pollSummaryServiceStreamPollSummaryServer) Send(m *PollSummary) error {
	return x.ServerStream.SendMsg(m)
}

var _PollSummaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "voting.summary.PollSummaryService",
	HandlerType: (*PollSummaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPollSummary",
			Handler:    _PollSummaryService_GetPollSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPollSummary",
			Handler:       _PollSummaryService_StreamPollSummary_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "poll-summary.proto",
}
