name: Build and Push
on: 
  push:
    branches:
      - master
jobs:
  buildSummary:
    name: Build Poll Summary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abvaden/demo-grpc-poll-summary-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: poll-summary-server/server/Dockerfile
        context: /
        tags: ${{ github.sha }}
  buildUser:
    name: Build User
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abvaden/demo-grpc-users-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: user-server/Dockerfile
        context: /
        tags: ${{ github.sha }}
  buildRecord:
    name: Build Record
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abvaden/demo-grpc-record-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: record-server/server/Dockerfile
        context: /
        tags: ${{ github.sha }}